---
title: ""
author: ""
date: ""

output:
  html_document:
    includes:
      in_header: header.html
---

# Ihar Valovich
## Data analyst
#### Warsaw

[iharvalovich.netlify.app](https://iharvalovich.netlify.app/)   
[iv.volovich@gmail.com](mailto:iv.volovich@gmail.com)   
(+48) 503310063

------

### Technical

1. R
1. Power BI
1. Microsoft SQL Server
1. SQL
1. R Shiny
1. R Markdown
1. Tidyverse


------

### Experience

**LLC ByTechSolution** *Product Manager* __2015 to 2020__
Analyze and explore data via a variety of statistical and descriptive techniques for business partners.Statistical analysis of data in the R system. Implementation (business analysis) of information systems of the MDC type (machine data collection) to monitor production efficiency and quality. Assessment of the effectiveness of the use of customer machines using the OEE (Overall Equipment Effectiveness) indicator.
	**Technical Environment** R, Power BI, Microsoft SQL Server.

**Carriage Building Works** *Quality Engineer* __2014 to 2015__
Monitor, control, and analyze product and process quality to meet internal and external customer requirements. Develop Control Plan to measure quality performance of machining operations. Designs, implements, evaluates, and revises, technical quality assurance protocols/methods for the inspecting and testing of in-process raw materials, production equipment, and finished products. Responsible for data collection, analysis, and reporting of all field quality data.Work across disciplines to identify, track, and resolve issues that impact product and customer experience quality.Maintenance of quality management systems (ISO 9001) with the required documentation.
	**Technical Environment** ERP software.

**JSC Mozyr Oil Refinery** *Mechanical Integrity Division Manager* __1995 to 2013__
Monitoring the operation of devices and taking action to prevent breakdowns. Monitoring and commissioning of devices, participation in their startup. Performing diagnostic and laboratory tests, measurements and technical expertise. Preparation of the schedule of technical inspections, analysis of causes and effects of failures using ERP software. Supervision over maintenance of technical efficiency of machines and production equipment. Participation in the implementation of investment and modernization projects of the plant. Supervision over technical and system documentation. Cooperation with the Production Department in the field of improving performance. Analysis of vibration data of rotating dynamic equipment.
	**Technical Environment** SAP PM, statistacal software.


------

### Projects

* **R Shiny dashboard**
	<a href=https://valovich.shinyapps.io/Simple_COVID_Tracker class=not-printed>COVID_Tracker</a>
	R Shiny dashboard which shows the number of people to have died with the coronavirus. It uses the downloadable data file from European Centre for Disease Prevention and Control updated daily and contains the latest available public data on COVID-19.

* **My own static website**
	<a href=https://iharvalovich.netlify.app class=not-printed>iharvalovich.netlify.app</a>
	My own static website which was built using:   
	* Repo on ```Github```   
	* Build website in ```RStudio``` using ```blogdown``` package and ```Hugo``` - framework for building  static websites   
	* Deploy website using ```Netlify``` - cloud computing service



------

### Education

**Master's degree (Technology of Mechanical Engineering)** __1990 to 1995__
	Belarusian National Technical University   
**Master's degree (Economics)** __1996 to 1999__
	Belarusian State Economic University   
**PhD (Control methods and diagnostics in mechanical engineering)** __2001 to 2004__
	PhD  school of the institute of applied physics in Belarus,
	
